<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE students SYSTEM "student.dtd">

<!--<!DOCTYPE students [

		<!ELEMENT students (student+) >
		<!ELEMENT student (name,age,sex)>
		<!ELEMENT name (#PCDATA)>
		<!ELEMENT age (#PCDATA)>
		<!ELEMENT sex (#PCDATA)>
		<!ATTLIST student number ID #REQUIRED>


		]>-->
<students>

	<student number="s001">
		<name>共饮一杯无</name>
		<age>23</age>
		<sex>superman</sex>
	</student>

	<student number="s002">
		<name>zjq</name>
		<age>18</age>
		<sex>man</sex>
	</student>

</students>
